version: '3.8'

services:
  banco1:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
  banco2:
    build:
      context: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
  banco3:
    build:
      context: .
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
